local E, L, C = select(2, ...):unpack()

C["Party"] = {
	["general"] = {
		["showAnchor"] = false,
		["player"] = false,
		["tooltip"] = false,
		["bgTrinket"] = false,
	},
	["position"] = {
		["detached"] = false,
		["uf"] = "auto",
		["arena"] = {
			["noTheme"] = false,
			["preset"] = "TOPRIGHT",
			["anchor"] = "TOPLEFT",
			["attach"] = "TOPRIGHT",
			["offsetX"] = 0,
			["offsetY"] = 0,
			["layout"] = "horizontal",
			["columns"] = 6,
			["breakPoint"] = 3,
			["displayInactive"] = true,
		},
		["party"] = {
			["preset"] = "TOPRIGHT",
			["anchor"] = "TOPLEFT",
			["attach"] = "TOPRIGHT",
			["offsetX"] = 0,
			["offsetY"] = 0,
			["layout"] = "horizontal",
			["columns"] = 6,
			["breakPoint"] = 3,
			["displayInactive"] = true,
		},
		["raid"] = {
			["preset"] = "TOPRIGHT",
			["anchor"] = "TOPLEFT",
			["attach"] = "TOPRIGHT",
			["offsetX"] = 0,
			["offsetY"] = 0,
			["layout"] = "horizontal",
			["columns"] = 6,
			["breakPoint"] = 3,
		},
		["manual"] = {
			["preset"] = "TOPRIGHT",
			["anchor"] = "TOPLEFT",
			["attach"] = "TOPRIGHT",
			["offsetX"] = 0,
			["offsetY"] = 0,
			["layout"] = "horizontal",
			["columns"] = 6,
			["breakPoint"] = 3,
			["displayInactive"] = true,
		},
		["position"] = {},
	},
	["icons"] = {
		["autoScale"] = false,
		["showCounter"] = true,
		["reverse"] = false,
		["desaturateActive"] = false,
		["scale"] = 0.8,
		["chargeScale"] = 1.1,
		["paddingX"] = 2,
		["paddingY"] = 2,
		["counterScale"] = 0.85,
		["swipeAlpha"] = 0.8,
		["inactiveAlpha"] = 1,
		["activeAlpha"] = 1,
		["displayBorder"] = true,
		["pixelPerfect"] = true,
		["twoPixelBorder"] = false,
		["borderColor"] = { r = 0, g = 0, b = 0 },
		--["disableReloadPopup"] = true,
		["showForbearanceCounter"] = true,
	},
	["highlight"] = {
		["glow"] = true,
		["glowBuffs"] = true,
		["anim"] = true,
		["glowBuffTypes"] = {
			["defensive"] = true,
			["immunity"] = true,
			["offensive"] = false,
			["others"] = false,
		},
		["markEnhanced"] = true,
	},
	["visibility"] = {
		["arena"] = true,
		["pvp"] = false,
		["party"] = true,
		["raid"] = false,
		["scenario"] = false,
		["none"] = false,
		["size"] = 5,
	},
	["priority"] = {
		["custom"] = 10,
		["trinket"] = 9,
		["racial"] = 8,
		["all"] = 7,
		["interrupt"] = 6,
		["cc"] = 5,
		["immunity"] = 4,
		["defensive"] = 3,
		["offensive"] = 2,
		["others"] = 1,
		["essence"] = 0,
	},
	["spells"] = {},
	["manualPos"] = {},
}
